/*
 * hal.c
 *
 *  Created on: Jun 30, 2024
 *      Author: earlybeasts
 */

#include <hal.h>

void HAL_IntiHardware(void)
{
	/* Setting up start-up conditions for PSRAM immediately after power up */
	L2HAL_MCU_ClockPortIn(HAL_QSPI_PORT1);
	L2HAL_MCU_ClockPortIn(HAL_QSPI_PORT2);

	GPIO_InitTypeDef GPIO_InitStruct;

	/* PSRAM CS -> HIGH */
	GPIO_InitStruct.Pin = HAL_PSRAM_CS_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_CS_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_CS_PORT, HAL_PSRAM_CS_PIN, GPIO_PIN_SET);

	/* PSRAM SIO0 -> LOW */
	GPIO_InitStruct.Pin = HAL_PSRAM_SIO0_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_SIO0_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_SIO0_PORT, HAL_PSRAM_SIO0_PIN, GPIO_PIN_RESET);

	/* PSRAM SIO1 -> LOW */
	GPIO_InitStruct.Pin = HAL_PSRAM_SIO1_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_SIO1_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_SIO1_PORT, HAL_PSRAM_SIO1_PIN, GPIO_PIN_RESET);

	/* PSRAM SIO2 -> LOW */
	GPIO_InitStruct.Pin = HAL_PSRAM_SIO2_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_SIO2_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_SIO2_PORT, HAL_PSRAM_SIO2_PIN, GPIO_PIN_RESET);

	/* PSRAM SIO3 -> LOW */
	GPIO_InitStruct.Pin = HAL_PSRAM_SIO3_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_SIO3_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_SIO3_PORT, HAL_PSRAM_SIO3_PIN, GPIO_PIN_RESET);

	/* PSRAM CLK -> LOW */
	GPIO_InitStruct.Pin = HAL_PSRAM_CLK_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(HAL_PSRAM_CLK_PORT, &GPIO_InitStruct);
	HAL_GPIO_WritePin(HAL_PSRAM_CLK_PORT, HAL_PSRAM_CLK_PIN, GPIO_PIN_RESET);
}
